# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FlightPlanner
                                 A QGIS plugin
 Flight planner let you plan and optimize your photogrammetric flight.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-09-22
        copyright            : (C) 2019 by Jakub Gruca
        email                : jakubmgruca@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FlightPlanner class from file FlightPlanner.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .flight_planner import FlightPlanner
    return FlightPlanner(iface)
